- name: Remove old container
  community.docker.docker_container:
    name: chatter-bot
    state: absent

- name: Clean old image
  file:
    path: /root/chatter-bot/
    state: absent

- name: Create chatter-bot directory
  file:
    path: /root/chatter-bot
    state: directory

- name: Copy image tar
  copy:
    src: chatter-bot.tar.gz
    dest: /root/chatter-bot/chatter-bot.tar.gz

- name: Copy secrets
  copy:
    src: secrets.env
    dest: /root/chatter-bot/secrets.env

- name: Load chatter-bot image
  community.docker.docker_image_load:
    path: "/root/chatter-bot/chatter-bot.tar.gz"

- name: Start chatter-bot
  community.docker.docker_container:
    name: chatter-bot
    image: chatter-bot:latest
    restart: true
    env_file: /root/chatter-bot/secrets.env
    ports:
      - "8081:3000"
