- name: Add HTTP(S) iptables rules
  iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT


- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    update_cache: true

- name: Enalbe netfilter-persistent
  systemd:
    name: netfilter-persistent
    enabled: true

- name: Save Rules
  shell: sudo netfilter-persistent save
