- name: Install apt source utilities
  apt:
    name:
      - debian-keyring 
      - apt-transport-https
      - curl
      - debian-archive-keyring 

- name: Add Caddy repository key
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /etc/apt/trusted.gpg.d/caddy.asc
    mode: '0644'
    force: true

- name: Add Caddy deb repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present

- name: Add Caddy deb-src repo
  apt_repository:
    repo: "deb-src [signed-by=etc/apt/trusted.gpg.d/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present

- name: Install caddy
  apt:
    name: caddy
    update_cache: true

- name: Ensure Caddy is enabled
  systemd:
    name: caddy
    enabled: true

- name: Deploy Caddyfile
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
  notify: Reload Caddy
